### ISSUE TITLE
some FAILED shaders

### ISSUE THREAD

**Issue by alatteri** [ManChicken1911/matchbox#2]
The following shaders fail to compile:

Ls_Vignette
y_comp

**Comment by ManChicken1911** [comment]
Yeah, the issue with both shaders are that they define a variable called "mix" which conflicts with the built-in GLSL function mix() and is a syntax error. They need to be fixed by the authors.

However Ls_Vignette doesn't seem to work anyway, at least on Linux, even if you fix the name collision -- it just outputs white for me. I haven't dug into his code further to try to figure out why. It could be one of those things that's working on Mac only? I'll send a note to Lewis about it and see.

I'll also send a note to Miles about y_comp and hopefully he can update it on logik-matchbook.

**Comment by ManChicken1911** [comment]
Found the problem with Ls_Vignette causing it to just output white, and a working version is now in the current Matchbook download.
